---
# Local PG snapshot name example:
# z-oracle1-u02.ansible123
#
# Replicated volume name example
# se-EMEA-EBC-FAm20-a:z-oracle1PG.ansible123.z-oracle1-u02
#
- name: Overwrite Database volume(s)
  uri:
    url: https://{{ arrayT.ip }}/api/{{ arrayT.api_version }}/volume/{{ item.value.target }}
    method: POST
    headers:
      Cookie: "{{ sessionT.set_cookie }}"
    validate_certs: "no"
    return_content: "yes"
    body:
        source: "{{ array.name}}:{{ sourceName }}.{{ suffix }}.{{ item.value.source }}"
        overwrite: "true"
    body_format: json
  with_dict: "{{ volmap }}"

