---
# Create Database Volume Tags
# Limit of 5 tags per Namespace
#
- name: Create Database tags in Oracle Namespace
  purefa_volume_tags:
    name: "{{ item.value.target }}"
    namespace: Oracle
    copyable: true
    kvp:
      - 'dbName:{{ tgt_db }}'
    fa_url: "{{ array.ip }}"
    api_token: "{{ array.array_token }}"
    state: present
  with_dict: "{{ tgtmap }}"
  ignore_errors: True
