---
# Perform PURE Flasharray Database snapshots
- name: Perform PURE database snapshot {{ suffix }}
  purefa_pgsnap:
    fa_url: "{{ array.ip }}"
    api_token: "{{ array.array_token }}"
    name: "{{ sourceName }}"
    suffix: "{{ suffix }}"
    state: present
  register: snap
