---
# Create Pure session
- name: Create PURE Session
  uri:
    url: https://{{ array.ip }}/api/{{ array.api_version }}/auth/session
    method: POST
    validate_certs: "no"
    return_content: "yes"
    body:
        api_token: "{{ array.array_token }}"
    body_format: json
  register: session
