---    
# Target databas server setup
- name: Copy change database name script
  template: src=templates/6_dbnewid.sh.j2 dest={{ tgt_dir }}/6_dbnewid.sh mode=0755

- name: Copy rename database files sql
  template: src=templates/rename.sql.j2 dest={{ tgt_dir }}/rename.sql mode=0644

- name: Copy rename db datafiles script
  template: src=templates/8_rendbfiles.sh.j2 dest={{ tgt_dir }}/8_rendbfiles.sh mode=0755

- name: Copy show db script
  template: src=templates/9_showDB.sh.j2 dest={{ tgt_dir }}/9_showDB.sh mode=0755

- name: Copy database shutdown script to target database server
  template: src=templates/shutdownDB.sh.j2 dest={{ tgt_dir }}/shutdownDB.sh mode=0755

- name: Copy database startup Mount script to target database server
  template: src=templates/5_startup.sh.j2 dest={{ tgt_dir }}/5_startup.sh mode=0755
    
- name: Copy database source init.ora files to target database server
  template: src=templates/src_init.ora.j2 dest={{ tgt_oh }}/dbs/init{{ src_db }}.ora mode=0755

- name: Copy database target init.ora files to target database server
  template: src=templates/tgt_init.ora.j2 dest={{ tgt_oh }}/dbs/init{{ tgt_db }}.ora mode=0755
