---
# Perform PURE Flasharray PG snapshot and Replicate
- name: perform PURE database snapshot {{ suffix }}
  uri:
    url: https://{{ array.ip }}/api/{{ array.api_version }}/pgroup
    method: POST
    headers:
      Cookie: "{{ session.set_cookie }}"
    validate_certs: "no"
    return_content: "yes"
    body:
        snap: "true"
        source: "{{ sourcePG }}"
        suffix: "{{ suffix }}"
        replicate_now: "true"
        apply_retention: "true"
    body_format: json
  ignore_errors: yes
  register: snap

#- debug:
#    msg: "source: {{ sourcePG }}"
